New modal
Yizong98/Housing_Proj pull request #100
Opened 2021-09-02 07:53 UTC by AnthonyM456

New modal component:

2021-09-03 01:52 UTC, bamit5 requested changes

2021-09-03 01:52 UTC, bamit5 commented on FrontEnd/src/components/basics/Modal/Modal.module.scss
> +  flex-direction: column;
flex-direction won't affect anything unless this is also `display: flex`

2021-09-03 01:52 UTC, bamit5 commented on FrontEnd/src/components/basics/Modal/Modal.tsx
> +        {(src || alt) && (
this should be only `src` not `src || alt`. consider if someone passes through an `alt` but not a `src`. then the image would be rendered without a `src` (not good).

if we think about it, we actually want to throw an error if an `alt` is passed through without a `src`. We can do this with discriminated types (difficult to do) OR better, we can do it by combining the `src` and `alt` into one object. Consider changing the src/alt props into an "image" prop which is an object { src: string; alt?: string }. Then you can handle the image prop by making it optional. This way, someone can pass nothing for the image, a src for the image, or both a src and alt.

Even better (this is optional, it's a bit harder to do), you can make the image prop like this:
`image?: string | ImageTypeName; // where ImageTypeName is the { src: string, alt?: string }`
so the user can pass only the src through the image (`image={srcVariable}`) or with an alt (`image={{ src: "", alt: "" }}`)

2021-09-03 01:52 UTC, bamit5 commented on FrontEnd/src/components/basics/Modal/Modal.tsx
> +        {(src || alt) && (
Also, what's the image supposed to be for? maybe make the "image" prop a more specific name to describe what it is better. Also, if the prop isn't clear, you should add an end of line comment describing what it's for (or a component header, which I've added for some but not all the components I wrote -- i just forgot to lol)

2021-09-03 01:52 UTC, bamit5 commented on FrontEnd/src/components/basics/Modal/Modal.tsx
> +  onClose: () => void;
onClose is inherited from MaterialUIModalProps, so there's no need to add it here

2021-09-03 01:52 UTC, bamit5 commented on FrontEnd/src/components/basics/Modal/Modal.tsx
> +          <div className={styles.text}>
I think this would be easier to read if you simply separated the label and caption logic:

```
{label && <div className={cn(styles.text, styles.label)}><h4>{label}</h4></div>}

{caption && <Subtitle1 className={cn(styles.text, styles.caption)}>{caption}</Subtitle1>
```
(there might be a few mistakes but something along these lines)

2021-09-03 01:52 UTC, bamit5 commented on FrontEnd/src/components/basics/Modal/Modal.tsx
> +  label?: string;
can you include in the PR what's the purpose of the label/caption and src/alt? idk what the purpose is so it would be helpful for me so I can give suggestions

2021-09-09 10:20 UTC, AnthonyM456 commented
Hello! Here's a bit of clarification and background for this PR :))

The purpose of the modal component revision was to make it easier for other developers to use the component without needing to constantly copy/paste and reuse the same parts. For most, if not all, modals, they are equipped with an image (modalGraphic), title, caption, and orange close button.

In the case of the make a post feature (currently in development), the team needs to use a modal in the flow. It was brought to my attention that for future use of the modal, it would be much better if developers could simply provide a title, caption, or image as a prop. This would be instead of having everything passed as children into the modal. Now, there would be no worry about any styling, formatting, and etc. It would be all handled in the component itself.

2021-09-10 04:01 UTC, bamit5 requested changes

2021-09-10 04:01 UTC, bamit5 commented on FrontEnd/src/components/basics/Modal/Modal.tsx
>        disableBackdropClick
You should pass onClose to MaterialUIModal as well. I think they have functionality so that if you clikc like ESC or something, it'll close it

2021-09-10 05:54 UTC, bamit5 requested changes

2021-09-10 05:54 UTC, bamit5 commented on FrontEnd/src/components/basics/Modal/Modal.tsx
> +  alt?: string;
alt is no longer necessary right?

2021-09-10 05:54 UTC, bamit5 commented on FrontEnd/src/components/basics/Modal/Modal.tsx
> +  onClose, //required function to close unique popup
nit: no need for this end of line comment either

2021-09-10 06:09 UTC, bamit5 approved these changes

2021-09-14 06:26 UTC, merged