XXXXXXXL PR: get ready for dino egg version make a post
Yizong98/Housing_Proj pull request #109
Opened 2021-09-23 06:51 UTC by Yizong98

I apologized. This is a super large PR so please take your time reviewing the file. This would not slow the launch time since I am hosting it using another non-customer-facing server so making sure the code is good and healthy is the top priority. You can skip the backend since I would write tests for it. Please review the frontend code and let me know what to change. Thanks!

2021-10-13 06:05 UTC, bamit5 commented on FrontEnd/src/hooks/swr/useStudentRoomData.ts
> +/**
new line above

2021-10-13 06:06 UTC, bamit5 commented on FrontEnd/src/hooks/useScrollDirection.ts
> +const useScrollDirection = () => {
new line above

2021-10-13 06:06 UTC, bamit5 commented on FrontEnd/src/hooks/useScrollDirection.ts
> +  useEffect(() => {
new line above

2021-10-13 06:06 UTC, bamit5 commented on FrontEnd/src/hooks/useScrollDirection.ts
> +  const [scrollDir, setScrollDir] = useState<string>('up');
probably should make the type `'up' | 'down'` instead of `string`

2021-10-13 06:08 UTC, bamit5 commented on FrontEnd/src/hooks/useScrollDirection.ts
> +    let lastScrollY = window.pageYOffset;
should have useRef instead of just using a variable in case the render re-runs (if it re-renders, it'll reset everything)

2021-10-13 06:08 UTC, bamit5 commented on FrontEnd/src/hooks/useScrollDirection.ts
> +    let ticking = false; // flag to make sure we only run event listener once in every AnimationFrame
same here

2021-10-13 06:10 UTC, bamit5 commented on FrontEnd/src/hooks/useScrollDirection.ts
> +    const threshold = 0;
should be out of the hook

2021-10-13 06:12 UTC, bamit5 commented on FrontEnd/src/hooks/useScrollDirection.ts
> +  return scrollDir;
new line above

2021-10-13 06:13 UTC, bamit5 commented on FrontEnd/src/pages/housing/landLordPost/[roomId].tsx
> +import { TriggerPageView } from '@components/ga';
should be able to import this from `@components` without the `/ga`

2021-10-13 06:17 UTC, bamit5 commented on FrontEnd/src/redux/slices/overlay.ts
> +  shouldOverlay: boolean;
if this is a redux slice for any overlay, then you should probably specify which overlay this one is referencing (same for the functions too)

2021-10-13 06:17 UTC, bamit5 commented on FrontEnd/src/redux/slices/post.ts
> +import { postingType } from '@components';
postingType should be capitalized

2021-10-13 06:19 UTC, bamit5 commented on FrontEnd/src/utils/room/availability.ts
> +  `${availMonth.slice(0, 3)} ${availYear} - ${untilMonth.slice(
this should probably be separated into several lines of code to increase readability

2021-10-13 06:21 UTC, bamit5 commented on FrontEnd/src/utils/room/room.ts
> +  let roomIdString;
make the var name more generic

2021-10-13 06:30 UTC, bamit5 commented on FrontEnd/src/pages/housing/studentPost/[roomId].tsx
> +  useEffect(() => {
Consider changing this to its own hook. Here's some idea of what it could look like:

```
// can use for a single param or multiple params
const useRouterParams = (id: string | []string): string | null => {
  const router = useRouter();
  const [params, setParams] = useState(); // can set params in here
  
  useEffect(() => {
    if (!router.isReady) return null;

    const param = parseQueryParam(); // can move the definition of parseQueryParam to the top of this file too. do this for each param in the parameter
    setParams(); // add param here into the params object
  }, [id, router]);
  
  return params
}
```

2021-10-13 06:49 UTC, bamit5 requested changes
Here's an initial review. Because there was a lot of repeated problems and it's hella long, i definitely missed some comments. ill come back to some of them in future reviews

2021-11-09 04:44 UTC, Yizong98 commented on FrontEnd/src/components/HouseCardList/HouseCard/HouseCard.tsx
> +    window.open(`/housing/studentPost/${id}`, '_blank');
it is already in a separate function, so I don't think using one additional function would improve readability. It is already a one-liner.

2021-11-09 04:51 UTC, Yizong98 commented on FrontEnd/src/components/HouseCardList/HouseCard/HouseCard.tsx
> +              {...{
the props names and the passed in variable names are the same

2021-11-09 04:53 UTC, Yizong98 commented on FrontEnd/src/components/HouseCardList/HouseCard/HouseCard.tsx
> +              {...{
https://stackoverflow.com/questions/51148064/reacts-props-with-the-same-name-as-their-value

2021-11-09 05:42 UTC, Yizong98 commented on FrontEnd/src/components/HouseCardList/HouseCardList.tsx
> +  return <HouseCardListUI roomIds={roomIds} postType="student" />;
great point. Not even in the current PR scope. I will add a TODO to future

2021-11-10 06:20 UTC, Yizong98 commented on FrontEnd/src/components/LandingPage/LandingPage.module.scss
> +  @include bp-down('md') {
this class only has include

2021-11-10 06:25 UTC, Yizong98 commented on FrontEnd/src/components/Layout/Layout.tsx
> +      <div className={cn(styles.layout, { 'd-none': ShouldOverlay })}>
yes, it would hide all the children. We need this for make a post preview

2021-11-10 06:28 UTC, Yizong98 commented on FrontEnd/src/components/Login/Login.module.scss
> +  border-radius: 0.625rem;
it wasn't in the design system. So should be same for now

2021-11-11 07:55 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/MakeAPost.module.scss
> +    opacity: 0.2;
no need for now. Not in the design system

2021-11-21 21:21 UTC, Yizong98 commented on FrontEnd/src/components/basics/WizardForm/WizardForm.tsx
> +  customModifierFuncs,
refine works. Marked as done

2021-11-21 21:53 UTC, Yizong98 commented on FrontEnd/src/components/basics/WizardForm/WizardForm.tsx
> +   * @param pageSwitch whether it is a page switch
it is used to distinguish the validations of the whole page vs just a change in the page. It should no longer be needed since we figured out how to use the refine approach to achieve our goal.

2021-11-22 06:43 UTC, Yizong98 commented on FrontEnd/src/components/basics/WizardForm/WizardForm.tsx
> +  cleanUpReset?: () => void; // must be provided to reset clean up
this is used to clean up the parent's state and yes a default reset function can help. We can add a default clean-up in the next PR since I am trying to fix the current PR.

2021-11-22 07:17 UTC, Yizong98 commented on FrontEnd/src/components/basics/WizardForm/WizardForm.tsx
> +  }, [cleanUpReset]);
This is exactly the functionality we want. cleanUpReset is working for the parent state, not resetting the current form. For example, cleanUpReset would only be defined once make a post succeeds, so it would be undefined at first. And yes we need to pass a "reset" function, but not in the scope. I changed the name to `externalCleanUp`

2021-11-22 07:37 UTC, Yizong98 commented on FrontEnd/src/components/basics/WizardForm/WizardForm.tsx
> +  }, [curIndex, children, cleanUpReset]);
this is not needed

2021-11-24 06:53 UTC, Yizong98 commented on FrontEnd/src/components/basics/WizardForm/WizardForm.tsx
> +  externalFunction?: (s: Partial<T>[]) => void; // external function for utilizing internal store and will be called during set store
corrected

2021-11-24 08:18 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/MakeAPost.tsx
> +  const { mutate } = useSWRConfig();
fixed

2021-11-30 08:11 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/MakeAPost.tsx
> +              setInitialStore(initialStoreArray); // clean up the form
changed its name. initialStore is misleading indeed. it is supposed to mirror whatever inside wizard form

2021-12-05 01:28 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/MakeAPost.tsx
> +            ...{
avoiding retyping since the keys and the corresponding values are the same

2021-12-05 04:35 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/Page1.tsx
> +interface PartProps {
absolutely. I agree

2021-12-18 21:45 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/Page3.tsx
> +    availMonth: z.string().nonempty(NON_EMPTY_ERR_MSG),
I don't recommend this even though it is good to use stricter checking for Zod, it isn't practical since we have to convert month to string and vice versa in order for TS to not complain. I think sticking with strings would be the most generic and practical way.

2021-12-19 21:10 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/Page4.tsx
> +  rentCost: z
I have tried the suggestion and I still recommend sticking with string with regex validation so that we can enable empty value => which isn't supported by .number()

2021-12-19 22:50 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/Page4.tsx
> +      isSingleLine={false}
isSingleLine must be provided based on Material UI Props

2021-12-19 23:17 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/Page4.tsx
> +const CostInput: FunctionComponent<InputProps> = ({
Hmmm I don't think we need to overgeneralize in this part. Let's keep the wizard generic

2021-12-19 23:21 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/Page4.tsx
> +      type="rentCost"
Yeah, I think I came up with a way to both abstract and enable type support. Should be resolved

2021-12-20 03:57 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/Page5.tsx
> +export const displayAmenities: Partial<keyof typeof amenityToIcon>[] = [
this just a selection of the constants in the constants folder so I believe it is fine

2021-12-26 06:35 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/PopUps/FailurePopUp.tsx
> +import React, { FunctionComponent } from 'react';
Let's keep them separate for now. The level of similarity isn't to the degree that combination of both is worth it.

2021-12-26 06:38 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/PopUps/index.ts
> +export { default as SuccessPopUp } from './SuccessPopUp';
Good point. Not in the scope of the current PR. We can do it the a follow-up PR

2021-12-26 06:45 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/PopUps/PopUp.module.scss
> +  border-radius: 0.9375rem;
same. It is now using a variable

2021-12-26 06:59 UTC, Yizong98 commented on FrontEnd/src/components/NewUserSetup/NewUserSetup.module.scss
> +  textarea {
nope

2021-12-27 18:59 UTC, Yizong98 commented on FrontEnd/src/components/MakeAPost/PopUps/PopUp.module.scss
> +  padding: 0.75rem 1.5rem;
it is needed to expand the padding to meet the design.

2021-12-27 20:24 UTC, Yizong98 commented on FrontEnd/src/components/StudentHouseProfile/StudentHouseProfile.tsx
> +      {...{
same as reduce repetition since they are of the same names

2021-12-27 20:33 UTC, Yizong98 commented on FrontEnd/src/components/basics/Alert/Alert.tsx
>    button?: string;
buttonText is good enuf. I think we want to keep the name generic

2021-12-27 21:15 UTC, Yizong98 commented on FrontEnd/src/components/basics/CheckBoxGroup/CheckBox/CheckBoxButton.module.scss
> +  border-radius: 0.25rem;
I added a variable for both. Great point

2021-12-27 22:40 UTC, Yizong98 commented on FrontEnd/src/components/basics/CheckBoxGroup/CheckBox/CheckBoxButton.tsx
>    withLabel: boolean;
absolutely. Thank you

2021-12-28 02:32 UTC, Yizong98 commented on FrontEnd/src/components/basics/Chip/Chip.tsx
> +  state: Partial<ChipState>;
well, it is Will's code. I have deleted it

2021-12-28 03:19 UTC, Yizong98 commented on FrontEnd/src/components/basics/DatePicker/DatePicker.tsx
>    const [focus, setFocus] = useState<'startDate' | 'endDate' | null>(null);
the default value is undefined. onFocusChange only takes null

2021-12-28 21:50 UTC, Yizong98 commented on FrontEnd/src/components/basics/GooglePlaceAutoComplete/GooglePlaceAutoComplete.tsx
> +interface GooglePlaceAutoCompleteProps extends Partial<PropTypes> {
u r right

2021-12-28 21:52 UTC, Yizong98 commented on FrontEnd/src/components/basics/GooglePlaceAutoComplete/GooglePlaceAutoComplete.tsx
> +            onSelect(address, '');
the second prop is the place ID. We don't need it

2021-12-29 19:35 UTC, Yizong98 commented on FrontEnd/src/components/basics/ImageUpload/ImageUpload.tsx
> +  initialFiles: File[];
no. The upstream has to provide it. we don't want it to be undefined

2021-12-29 19:38 UTC, Yizong98 commented on FrontEnd/src/components/basics/ImageUpload/ImageUpload.tsx
>    const UploadSizeLimit = 6;
let's use snake case all caps for constants: https://stackoverflow.com/questions/40291766/naming-convention-for-const-object-keys-in-es6

2021-12-29 21:09 UTC, Yizong98 commented on FrontEnd/src/components/basics/ImageUpload/ImageUpload.tsx
> +        {files.length !== UploadSizeLimit &&
no, it should be smaller. either !== or < works

2021-12-29 21:13 UTC, Yizong98 commented on FrontEnd/src/components/basics/Loading/Loading.module.scss
> +  z-index: 1300;
no need for now. It should be in a project where we agree on a range of z-index. Added a TODO

2021-12-29 21:15 UTC, Yizong98 commented on FrontEnd/src/components/basics/Loading/Loading.module.scss
> +  background-color: rgba(0, 0, 0, 0.34);
no need. It is only used here

2021-12-29 21:15 UTC, Yizong98 commented on FrontEnd/src/components/basics/Loading/Loading.module.scss
> +  z-index: -1;
same as the reply of needing agreement on a set of z-indexes

2021-12-30 07:23 UTC, Yizong98 commented on FrontEnd/src/components/basics/Modal/Modal.tsx
> +          <div>
it is not reused a lot of times to the point that we need a basic component. The icon appears two times and the button wrapper appears twice. Also the code is pretty simple so we probably don't need a basic component in this case.

2021-12-30 07:33 UTC, Yizong98 commented on FrontEnd/src/components/basics/RadioGroup/RadioButton/RadioButton.module.scss
> +  z-index: 2;
doesn't seem necessary

2021-12-30 07:35 UTC, Yizong98 commented on FrontEnd/src/components/basics/RadioGroup/RadioButton/RadioButton.module.scss
>    border: 0.125rem solid rgba(170, 170, 170);
the rest doesn't have to be turned into vars

2021-12-30 07:38 UTC, Yizong98 commented on FrontEnd/src/components/basics/RadioGroup/RadioButton/RadioButton.tsx
>    value: string; // required for value extracting
same reasoning. We still need cases where we have a value but don't want a label

2021-12-30 07:52 UTC, Yizong98 commented on FrontEnd/src/components/basics/RadioToggleGroup/RadioToggle/RadioToggle.module.scss
>    -webkit-transition: 0.4s;
it is not used anywhere else from now but we can make the seconds a variable

2021-12-30 07:55 UTC, Yizong98 commented on FrontEnd/src/components/basics/StickyBar/StickyBar.module.scss
> +  background: rgba(255, 255, 255, 0.74);
no need

2021-12-30 07:58 UTC, Yizong98 commented on FrontEnd/src/components/basics/StickyBar/StickyBar.tsx
> +        {scrollDirection === 'up' ? children : undefined}
it would disappear on the down scroll so it is not a problem. Do you mean using animation to transition the children to disappear?

2021-12-30 22:40 UTC, Yizong98 commented on FrontEnd/src/components/basics/Toggle/Toggle.module.scss
>      border: 0.0625rem $primary-300-color solid;
doesn't seem needed now

2021-12-30 23:03 UTC, Yizong98 commented on FrontEnd/src/components/basics/ToggleSwitchBar/ToggleSwitchBar.module.scss
> +  border: 0.0625rem solid #dedede;
don't think so

2021-12-30 23:03 UTC, Yizong98 commented on FrontEnd/src/components/basics/ToggleSwitchBar/ToggleSwitchBar.module.scss
> +  border-radius: 3.125rem;
no need for now

2021-12-30 23:08 UTC, Yizong98 commented on FrontEnd/src/components/basics/ToggleSwitchBar/ToggleSwitchItem/ToggleSwitchItem.module.scss
> +  box-shadow: 0 0.0625rem 0.5rem rgba(0, 0, 0, 0.18);
abstract the color rgba(0, 0, 0, 0.18). Other is fine to give flexibility

2021-12-30 23:09 UTC, Yizong98 commented on FrontEnd/src/components/basics/ToggleSwitchBar/ToggleSwitchItem/ToggleSwitchItem.module.scss
> +  border-radius: 3.125rem;
no need for now

2021-12-31 01:44 UTC, Yizong98 commented on FrontEnd/src/components/basics/Tooltip/Tooltip.module.scss
>    box-shadow: 0rem 0.0625rem 0.5rem rgba(0, 0, 0, 0.18);
no need

2021-12-31 01:45 UTC, Yizong98 commented on FrontEnd/src/components/basics/Tooltip/Tooltip.module.scss
>    border-radius: 0.5rem;
yes

2021-12-31 21:22 UTC, Yizong98 commented on FrontEnd/src/hooks/useScrollDirection.ts
> +    let lastScrollY = window.pageYOffset;
it is meant to reset everything. https://stackoverflow.com/questions/62497110/detect-scroll-direction-in-react-js

2022-01-01 00:08 UTC, Yizong98 commented on FrontEnd/src/redux/slices/overlay.ts
> +  shouldOverlay: boolean;
it is supposed to be generic. I will add some more comments tho

2022-01-21 05:30 UTC, closed without merging