style: onboarding flow
Yizong98/Housing_Proj pull request #148
Opened 2022-03-24 18:05 UTC by dhylan01

- Used figma outline to fit new onboarding flow
- Created new input line with a different style
- Changed styling of current pages to now have three with different colors and layouts

2022-03-26 04:24 UTC, Yizong98 requested changes

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/NewUserSetup/EducationPage.tsx
> +// NOTE: need the "as FunctionComponent" since typescript doesn't know that WizardForm parent component will
Please delete the irrelevant copied and pasted code

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/NewUserSetup/NewUserSetup.module.scss
> +  justify-content: center !important;
sorry but don't use `!important` since it is a very bad practice. There are several places in our codebase where we abuse this property. Please don't follow those examples. Let's try to use a way without `!important`

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/NewUserSetup/NewUserSetup.module.scss
> +.nameAskEducation {
run your prettier?

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/NewUserSetup/NewUserSetup.module.scss
> +  margin-top: 8%;
Have we verified that this worked with super large screen => 5000+ px width? percentage can be tricky with large screen

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/NewUserSetup/NewUserSetup.module.scss
> +  background-color: F8E6D8;
can we verify this works without the `#` prefix?

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/NewUserSetup/NewUserSetup.module.scss
> +  margin-left: -10%;
same here for verification

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/NewUserSetup/NewUserSetup.module.scss
> +  margin-top: 5%;
same

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/NewUserSetup/NewUserSetup.module.scss
> +  padding-bottom: 20px;
space between

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/NewUserSetup/PhonePage.tsx
> +// NOTE: need the "as FunctionComponent" since typescript doesn't know that WizardForm parent component will
same here. no need for comments

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/basics/InputLine/InputLine.stories.tsx
> +import React, { ComponentProps } from 'react';
can we write a story for this?

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/basics/InputLine/InputLine.tsx
> +const Input: FunctionComponent<InputProps> = ({
shouldn't we call it "InputLine"?

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/basics/InputLine/InputLine.tsx
> +export default Input;
same here?

2022-03-26 04:24 UTC, Yizong98 commented on FrontEnd/src/components/basics/InputLine/InputLine.module.scss
> +      //border-color: $primary-light-color;
delete uncommented code

2022-03-29 03:36 UTC, dhylan01 commented
I committed the changes to the new branch and I hope they are updated for the PR

2022-03-29 22:19 UTC, Yizong98 approved these changes

2022-03-29 22:20 UTC, merged