style: add design token constants
Yizong98/Housing_Proj pull request #154
Opened 2022-04-11 23:42 UTC by michaelliann

2022-04-18 05:45 UTC, AnthonyM456 approved these changes

2022-04-18 06:01 UTC, Yizong98 requested changes
https://sass-lang.com/documentation/at-rules/function
https://sass-lang.com/documentation/modules/math

use functions and math

2022-05-01 06:48 UTC, Yizong98 submitted a review, later dismissed

2022-05-01 06:48 UTC, Yizong98 commented on FrontEnd/src/assets/scss/utils/_global-vars.scss
> + * STYLE GUIDE Foundation/Spacing boxes
delete this

2022-05-01 06:48 UTC, Yizong98 commented on FrontEnd/src/assets/scss/utils/_functions.scss
> +@function spacing($base, $multiplier) {
this doesn't make sense since it is a division and not multiplication. Also you just need one parameter since the 100 denominator is a constant.

Why not do: 

```
@return math.div($base, 100)
```

2022-05-03 02:36 UTC, Yizong98 approved these changes

2022-05-03 02:36 UTC, merged