Calendar picker
Yizong98/Housing_Proj pull request #88
Opened 2021-07-08 19:47 UTC by CrisZong

1. add gtm & breakpoint & react ga to package.json
2. finish calendar picker

what is left to be done: move the UI manual testing to storybook rather than import to existing UI

2021-07-09 06:00 UTC, bamit5 requested changes
Great job, I noticed a few small things you can do to tidy up the code better. If you disagree with any of them, text me and let's discuss. I noticed your prettier doesn't seem to be working, can you try to fix that? You might have to give it permission under your notifications

2021-07-09 06:00 UTC, bamit5 commented on FrontEnd/src/components/basics/Calendar/index.ts
> +export * from './DatePicker';
Is your prettier working? there should automatically be a new line at the end of the file because of prettier. Please make sure it's working and then re-save all the files you were working on to format them correctly

2021-07-09 06:00 UTC, bamit5 commented on FrontEnd/src/components/basics/Calendar/DatePicker.tsx
> +function DatePicker() {
This should be an arrow function:
() => { return; }

to be consistent with the rest of the components we have

2021-07-09 06:00 UTC, bamit5 commented on FrontEnd/src/components/basics/Calendar/DatePicker.tsx
> +  };
You should run prettier formatter on this file. There should be a new line between the handleOnDateChange definition and the return statement for readability (picking at the small things).

2021-07-09 06:00 UTC, bamit5 commented on FrontEnd/src/components/basics/Calendar/DatePicker.tsx
> +      onDatesChange={handleOnDateChange}
Consider using an arrow function instead of handleOnDateChange because all you would need to do is this following:
onDatesChange={({ startDate, endDate }) => setDateRange({ startDate, endDate })}

which (in my opinion) is easier to read. This way, you don't need all the extra typescript in the function definition. Also, since the onDatesChange handler and setDateRange function have matching parameter types, you might be able to do this:

onDatesChange={setDateRange}

I'm not sure, but you should try it out. Let me know if it works!

2021-07-09 06:00 UTC, bamit5 commented on FrontEnd/src/components/basics/Calendar/DatePicker.tsx
> +      onFocusChange={(focus) => setFocus(focus)}
Try to do onFocusChange={setFocus}
not sure if it'll work but I think it might since the parameter types of the onFocusChange handler and setFocus function match up

2021-07-09 06:00 UTC, bamit5 commented on FrontEnd/src/components/basics/Calendar/DatePicker.tsx
> +      startDateId="startDateMookh"
why "startDateMookh" and "endDateMookh"? Is that a typo? If not, maybe add a comment explaining why the strange spelling

2021-07-09 06:00 UTC, bamit5 commented on FrontEnd/src/components/basics/Calendar/DatePicker.tsx
> +  const [focus, setFocus] = useState<'startDate' | 'endDate' | null>(null);
No need to pass null as an argument. Providing no argument to useState will default the initial value to null.

2021-07-09 16:56 UTC, Yizong98 commented on FrontEnd/src/components/basics/Calendar/index.ts
> +export * from './DatePicker';
done

2021-07-09 17:39 UTC, Yizong98 commented on FrontEnd/src/assets/scss/global/_theme.scss
> +.btn-primary {
deleted the class

2021-07-09 17:39 UTC, Yizong98 commented on FrontEnd/src/assets/scss/global/_theme.scss
> +// override react-dates style here
resolved

2021-07-09 17:42 UTC, Yizong98 commented on FrontEnd/src/components/basics/Calendar/DatePicker.module.scss
> +        color: #484848;
we don't need the color as it turns out. I deleted it

2021-07-17 01:38 UTC, bamit5 requested changes
just comments and folder change

2021-07-17 03:20 UTC, Yizong98 commented on FrontEnd/src/assets/scss/global/packages/_react-dates.scss
> +// Will edit selected date or the endpoints of a range of dates
It is totally fine. I just deleted the comment since I found it the variable name is self-explanatory

2021-07-31 03:44 UTC, merged