auto_email
Yizong98/Housing_Proj pull request #91
Opened 2021-08-13 01:39 UTC by taekunkim

Current pull request does not include function abuse detection because cache system has not been set up yet.

2021-08-15 05:30 UTC, Yizong98 requested changes
Overall, amazing work, and I can clearly see the dedication to the autoemail! Just need a few tweaks and it should be good for now!

2021-08-15 05:30 UTC, Yizong98 commented on BackEnd/app/util/auto_email/auto_email.py
> +    yag = yagmail.SMTP('yijianzong@gmail.com', oauth2_file='../../../.env/oauth2_creds.json')
this is not an ideal way to store email and credential information. The info, if merged, will be exposed to the whole Internet since it is open source. A better method could be found here: https://github.com/Yizong98/Housing_Proj/blob/master/BackEnd/app/util/env_setup.py

2021-08-15 05:30 UTC, Yizong98 commented on BackEnd/app/util/auto_email/auto_email.py
> +            if all(isinstance(item, str) for item in argument):
this logic can be further simplified, if not all, then do sth

2021-08-15 05:30 UTC, Yizong98 commented on BackEnd/app/util/auto_email/auto_email.py
> +            if all(isinstance(item, str) for item in argument):
normally it is not recommendable to use pass

2021-08-15 05:30 UTC, Yizong98 commented on BackEnd/app/util/auto_email/auto_email.py
> +    from yagmail.validate import validate_email_with_regex
these weren't used anywhere, please delete them.

2021-08-15 05:30 UTC, Yizong98 commented on BackEnd/app/util/auto_email/auto_email.py
> +def __check_abused(ip_address):
please delete the commented code and add a comment saying a TODO after cache server

2021-08-15 05:30 UTC, Yizong98 commented on BackEnd/app/util/auto_email/auto_email.py
> +    :param priority: boolean value; if True, suppresses exception
I like the priority flag!

2021-08-15 05:30 UTC, Yizong98 commented on BackEnd/app/util/auto_email/test.py
> +    # def test_multiple_addresses(self):
I understand the tests will be relevant once the cache server is up but really for now let's delete them since it is not a good practice to have commented code

2021-08-16 03:00 UTC, taekunkim commented on BackEnd/app/util/auto_email/auto_email.py
> +            if all(isinstance(item, str) for item in argument):
```
    # check if email addresses are string
    for argument in [to, cc, bcc]: 
        if not isinstance(argument, (type(None), str)):
            if isinstance(argument, list):
                if not(all(isinstance(item, str) for item in argument)): 
                    raise ValueError('Invalid parameter type')
```
Would this work? CC and BCC can be a string, a list of strings, or ```None```, so it's kind of complicated to check whether all of the items are in the type of ```str```.

2021-08-16 04:49 UTC, Yizong98 commented on BackEnd/app/util/auto_email/auto_email.py
> +            if all(isinstance(item, str) for item in argument):
what I meant is to replace line 78 with if not all(isinstance(item, str) for item in argument), so that you don't have to use pass

2021-11-16 06:01 UTC, closed without merging