Filter features implemented individually (helper functions)
Yizong98/Housing_Proj pull request #93
Opened 2021-08-14 20:27 UTC by anyachandorkar

2021-08-15 06:53 UTC, Yizong98 requested changes
It is an amazing PR!! BRAVO! Just need some little tweaks to get approval. I can definitely see all the efforts put in here.

2021-08-15 06:53 UTC, Yizong98 commented on BackEnd/app/filter/filter.py
> +            bed_count = room_type["Bedrooms"][0:-1]
I think you can use room_type["Bedrooms"][:-1]

2021-08-15 06:53 UTC, Yizong98 commented on BackEnd/app/filter/filter.py
> +        if((not bath_count.replace(".","",1).isdigit())):
well done

2021-08-15 06:53 UTC, Yizong98 commented on BackEnd/app/filter/filter.py
> +            time_per = distance[1:-5]
add a comment to explain the maximum value is 99999, five digit numbers

2021-08-15 06:53 UTC, Yizong98 commented on BackEnd/app/filter/filter.py
> +        if(int(time_per)<0):
isdigit already verifies it is a positive number. So It is fine to delete this check

2021-08-15 06:53 UTC, Yizong98 commented on BackEnd/app/filter/filter_json.py
> +class JSONFilter(object):
inherit the Filter! This is the exciting part.

2021-08-15 06:53 UTC, Yizong98 commented on BackEnd/app/filter/filter_json.py
> +        intersection = range(max(arr_rent[0], criteria[0]), min(
this is a mind-blowing technique. Bravo!

2021-08-15 06:53 UTC, Yizong98 commented on BackEnd/app/filter/filter_json.py
> +from app.util.util import *
don't import *.  https://docs.google.com/document/d/1Gps_3J-Nu4ld0GVEEV3YXGUrykqKgmGivcOp7UWlTKI/edit#heading=h.litxuvobnld5

2021-08-15 06:53 UTC, Yizong98 commented on BackEnd/app/filter/filter_json.py
> +        return bool_bed & bool_bath
exactly what I meant. thanks!

2021-08-15 06:53 UTC, Yizong98 commented on BackEnd/app/filter/filter_json.py
> +            return (int(input_str[1:-5]), operator.ge)
same explanation needed here

2021-08-15 06:53 UTC, Yizong98 commented on BackEnd/app/filter/filter_json.py
> +            if(listing_availability<criteria):
nested if elses are additional layers of abstractions. Think of different ways to make it more readable

2021-08-15 06:53 UTC, Yizong98 commented on BackEnd/app/filter/filter_json.py
> +            if(listing_availability<criteria):
bigger or equal is fine to address edge case. since it is latest acceptable

2021-08-15 21:24 UTC, tedfeng424 commented on BackEnd/app/filter/filter.py
> +            time_per = distance[1:-5]
wait where does 99999 come from?

2021-08-16 04:50 UTC, Yizong98 commented on BackEnd/app/filter/filter.py
> +            time_per = distance[1:-5]
as in five digits

2022-05-03 23:45 UTC, closed without merging